### ISSUE TITLE
UTF8 StackOverflowError during backup

### ISSUE THREAD

**Issue by user2684** [user2684/ZipSnapNG#178]
Exception in thread "Thread-8" java.lang.StackOverflowError
	at sun.nio.cs.UTF_8.updatePositions(UTF_8.java:58)
	at sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(UTF_8.java:392)
	at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:447)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:544)
	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:240)
	at java.lang.StringCoding.encode(StringCoding.java:272)
	at java.lang.String.getBytes(String.java:946)
	at java.io.UnixFileSystem.list(Native Method)
	at java.io.File.list(File.java:973)
	at java.io.File.listFiles(File.java:1051)
	at com.backup.zipsnap.ng.util.FileIO.listFiles(FileIO.java:669)
	at com.backup.zipsnap.ng.util.FileIO.browseDirectory(FileIO.java:618)

**Comment by user2684** [comment]
at com.backup.zipsnap.ng.util.FileIO.browseDirectory(FileIO.java:654) repating multiple times

**Comment by user2684** [comment]
loop identified in /Applications/XCode.app/Contents

**Comment by user2684** [comment]
Beofre scanning a directory, check if it is already into dirContents
